config/routes.rb
Rails.application.routes.draw do

  root 'static#home'
  get '/dashboard', to: 'static#dashboard', as: 'dashboard'

  resources :users do
    # resources :appointments, only: [:index]
    resources :clients, only: [:new]
  end

  resources :clients, only: [:create, :edit, :update, :index, :show, :destroy] do
    resources :appointments, only: [:edit]
  end

  resources :notes, only: [:index, :create]

  delete '/notes', to: 'notes#destroy'

  resources :appointments, only: [:index, :update]
  resources :sessions, only: [:create]

  get 'clients/:id/appointment_complete', to: 'clients#appointment_complete', as: 'appointment_complete'
  patch 'clients/:id/update_progress', to: 'clients#update_progress', as: 'update_progress'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Validations

  has_many :appointments
  has_many :clients, through: :appointments

  validates :name, :email, presence: true
  validates :email, uniqueness: true, email: true
  validates :password, length: { minimum: 8 }
  has_secure_password

  # Creates or logs in user via Facebook
  def self.from_omniauth(auth)
    self.where(:uid => auth["uid"]).first_or_create do |user|
      user.name = auth["info"]["name"]
      user.email = "#{auth["uid"]}@#{auth["provider"]}.com"
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.password = SecureRandom.hex(8)
      user.password_confirmation = user.password
      user.save!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_logged_in?

  # User Signup form
  def new
    @user = User.new
  end

  # Submission of User Signup Form
  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/new.html.erb
<div class="form-container">
  <%= render partial: 'layouts/errors', locals: { object: @user } %>
  <h1>New Account Form:</h1>
  <br></br>

  <%= form_for @user do |f| %>
    <div class="grid signup-login">
      <div class="box">
        <%= f.label :name, "Enter Your Name:" %>
        <br></br>
        <%= f.text_field :name %>
      </div>
        
      <div class="box">
        <%= f.label :email, "Enter Your Email:" %>
        <br></br>
        <%= f.text_field :email %>
      </div>
        
      <div class="box">
        <%= f.label :password, "Password (Must be at least 8 char.):" %>
        <br></br>
        <%= f.password_field :password %>
      </div>
    </div>
    <%= f.submit "Create Account", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Your Clients:</h1>
<br></br>
<% @user.clients.each do |client| %>
  <%= link_to "#{client.name}", client_path(client) %>
<% end %>