config/routes.rb
Rails.application.routes.draw do

  root 'static#home'
  get '/dashboard', to: 'static#dashboard', as: 'dashboard'

  resources :users do
    # resources :appointments, only: [:index]
    resources :clients, only: [:new]
  end

  resources :clients, only: [:create, :edit, :update, :index, :show, :destroy] do
    resources :appointments, only: [:edit]
  end

  resources :notes, only: [:index, :create]

  delete '/notes', to: 'notes#destroy'

  resources :appointments, only: [:index, :update]
  resources :sessions, only: [:create]

  get 'clients/:id/appointment_complete', to: 'clients#appointment_complete', as: 'appointment_complete'
  patch 'clients/:id/update_progress', to: 'clients#update_progress', as: 'update_progress'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
end

app/models/client.rb
class Client < ApplicationRecord
  include ActiveModel::Validations

  has_many :appointments
  has_many :weight_histories
  has_many :users, through: :appointments
  has_many :notes
  
  validates :name, :email, :phone, :age, :weight, :goal, presence: true
  validates :email, uniqueness: true, email: true
  validates :age, numericality: { greater_than: 0, less_than: 100 }
  validates :weight, numericality: { greater_than: 0 }
  validates :phone, phone: true

  # Returns client with largest progress attribute
  def self.most_progress
    order('progress DESC').first
  end

  # Returns client with most completed appointments
  def self.most_dedicated
    order('completed_appointments DESC').first
  end

  # Sums up all weight changes documented via the client's weight histories and sets that sum equal to the
  # client's progress attribute
  def update_progress
    progress = 0
    self.weight_histories.each do |w|
      progress += w.weight_recording
    end
    self.update(progress: progress)
  end

  # Adds 1 to client's completed appointments
  def complete_appointment
    self.update(completed_appointments: self.completed_appointments += 1)
  end

  # Takes difference of old and new weights and creates a weight history object to document progress
  def document_progress(new_weight, old_weight)
    if self.goal == "Lose Weight"
      self.weight_histories.create(weight_recording: (old_weight - new_weight))
    elsif self.goal == "Gain Weight"
      self.weight_histories.create(weight_recording: (new_weight - old_weight))
    end
  end

  # Custom attribute setter for nested appointment form in client form
  def appointments_attributes=(appointments_attributes)
    # If submitted client is valid
    if self.valid?
      appointments_attributes.values.each do |appointment_attributes|
        # Clients have only 1 associated appointment object. Instead of creating new objects
        # we simply update the date attribute once an appointment is completed
        if self.appointments.last != nil
          self.appointments.last.update(appointment_attributes)
        else
          # Create new appointment object and make it belong to new client
          appointment = Appointment.create(appointment_attributes)
          self.appointments << appointment
        end
      end
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :login_required
  before_action :find_and_set_client, only: [:show, :edit, :appointment_complete, :update_progress, :update, :destroy]

  # Render current user's clients to the dashboard via AJAX
  def index
    @clients = current_user.clients
    render json: @clients
  end

  # New Client form
  def new
    @client = Client.new
    @appointment = @client.appointments.build
  end

  # New Client form submission
  def create
    # Create new client object, with nested appointment object
    @client =  Client.new(client_params)
    # Set the new appointment's user_id equal to the current_user's id. This completes the association
    # between the current user and client, with the appointment acting as a join table
    @client.appointments.update(user_id: current_user.id)
    if @client.save
      redirect_to client_path(@client)
    else
      redirect_to new_user_client_path(current_user), alert: "Error(s): #{@client.errors.full_messages.join(', ')}."
    end
  end

  # Client Show page
  def show
    # Create new note object for AJAX note form
    @note = Note.new
    # Get notes belonging to client if any exist
    @notes = @client.notes if @client.notes
    # Can be rendered via html or AJAX
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @client }
    end
  end

  # Client Edit page
  def edit
  end

  # Action triggered when "Appointment Complete" button is clicked
  def appointment_complete
  end

  # Submission of appointment_complete form
  def update_progress
    # Store previous weight in @old_weight before updating
    @old_weight = @client.weight
    if @client.update(client_params)
      # Start documenting progress once client has completed > 1 appointment
      if @client.completed_appointments != 0
        @client.document_progress(client_params[:weight].to_i, @old_weight)
        @client.update_progress
      end
      # Add 1 to client's completed appointments
      @client.complete_appointment
      redirect_to client_path(@client)
    else
      render :appointment_complete
    end
  end

  # Submission of client edit form
  def update
    if @client.update(client_params)
      redirect_to client_path(@client)
    else
      render :edit
    end
  end

  # Remove client and associated resources from db
  def destroy
    @client.appointments.destroy_all
    @client.weight_histories.destroy_all
    @client.destroy
    redirect_to dashboard_path, alert: "Client removed."
  end

  private

  # Finds client in db belonging to current user based on url parameters
  def find_and_set_client
    @client = current_user.clients.find_by(id: params[:id])
    if @client.nil?
      redirect_to dashboard_path, alert: "Client not found."
    end
  end

  def client_params
    params.require(:client).permit(:id, :name, :email, :phone, :age, :weight, :goal, :appointments_attributes => [
      :id,
      :user_id,
      :client_id,
      :date
      ])
  end
end

app/helpers/client_helper.rb
module ClientHelper

  # If on clients index, print client name as link to show page, otherwise just print the name
  def client_name(client)
    if current_page?(clients_path)
      link_to client.name, client_path(client)
    else
      client.name
    end
  end

  # Renders form fields for nested appointment if current page is new client form or appointment complete form
  def appointment_fields(form, client, appointment)
    if current_page?(new_user_client_path(current_user)) || current_page?(appointment_complete_path(client))
      render partial: "appointment_fields", locals: {f: form, appointments: appointment, client: client}
    end
  end

  # Renders appropriate label for appointment_fields based on current page
  def appointment_field_label(appointment, client)
    if current_page?(new_user_client_path(current_user))
      appointment.label :date, "Schedule First Appointment:"
    elsif current_page?(appointment_complete_path(client))
      appointment.label :date, "Schedule Next Appointment:"
    end
  end

  # Prints client's progress toward their goal on show page
  def client_progress(client)    
    case client.goal
    when "Lose Weight"
      content_tag(:h4, "Progress: #{client.progress} lbs. Lost", :id => "progress")
    when "Gain Weight"
      content_tag(:h4, "Progress: #{client.progress} lbs. Gained", :id => "progress")
    end 
  end

  # Presents logic determined by most_dedicated class method
  def most_dedicated_client(clients)
    clients.most_dedicated.name if clients.most_dedicated != nil
  end

  # Presents logic determined by most_progree class method
  def most_progressed_client(clients)
    clients.most_progress.name if clients.most_progress != nil
  end
end

app/views/clients/_appointment_fields.html.erb
<%= f.fields_for :appointments do |app| %>
  <%= appointment_field_label(app, client) %>
  <br></br>
  <%= app.datetime_select :date, order: [:month, :day, :year, :hour], ampm: true %>
<% end %>
<br></br>

app/views/clients/_form.html.erb
<%= render partial: 'layouts/errors', locals: { object: @client } %>
<%= form_for @client do |f| %>
  <div class="grid client-partial">
    <div class="box">
      <%= f.label :name, "Name:" %>
      <br></br>
      <%= f.text_field :name %>
      <br></br>
      <%= f.label :email, "Email: (name@email.com)" %>
      <br></br>
      <%= f.text_field :email %>
      <br></br>
      <%= f.label :phone, "Phone Number: (XXX-XXX-XXXX)" %>
      <br></br>
      <%= f.telephone_field :phone %>
    </div>
      
    <div class="box">
      <%= f.label :age, "Age:" %>
      <br></br>
      <%= f.number_field :age %>
      <br></br>
      <%= f.label :weight, "Weight: (lbs.)" %>
      <br></br>
      <%= f.number_field :weight %>
      <br></br>
      <%= f.label :goal, "Client Goal:" %>
      <br></br>
      <%= f.select :goal, ["Lose Weight", "Gain Weight"] %>
    </div>
      
    <div class="box">
      <%= appointment_fields(f, @client, @appointment) %>
      <%= f.submit "Submit", class: "btn btn-primary btn-lg btn-block" %>
    </div>
  </div>
<% end %>

app/views/clients/appointment_complete.html.erb
<%= render partial: 'layouts/errors', locals: { object: @client } %>
<%= form_for @client, :url => url_for(:controller => 'clients', :action => 'update_progress') do |f| %>
  <% if @client.completed_appointments != 0 %>
    <%= f.label :weight, "Enter Your Client's Current Weight:" %>
    <br></br>
    <%= f.number_field :weight %>
    <br></br>
  <% else %>
    <h4><%= client_name(@client) %> has completed his/her first appointment.</h4>
  <% end %>
  <%= appointment_fields(f, @client, @client.appointments.last) %>
  <%= f.submit %>
<% end %>

app/views/clients/edit.html.erb
<div class="form-container">
  <h1>Edit Client:</h1>
  <br></br>
  <%= render 'form' %>
</div>

app/views/clients/new.html.erb
<div class="form-container">
  <h1>Add Client:</h1>
  <br></br>
  <%= render 'form' %>
</div>

app/views/clients/show.html.erb
<button id="previous" data-id="<%= @client.id %>" class="btn btn-secondary btn-sm">Previous</button>
<button id="next" data-id="<%= @client.id %>" class="btn btn-secondary btn-sm">Next</button>
<br></br>
<div class="grid show-view">
  <div class="box">
    <%= link_to "Edit Client", edit_client_path(@client), class: "btn btn-primary", id: "edit-client"  %>
    <%= link_to "Remove Client", @client, method: :delete, class: "btn btn-danger", id: "remove-client", data: { confirm: "Are you sure you want to remove this client?" } %>
    <h2 id="client-name"><%= client_name(@client) %></h2><br>
    <h4 id="email">Email: <%= @client.email %></h4><br>
    <h4 id="phone">Phone: <%= @client.phone %></h4><br>
    <h4 id="age">Age: <%= @client.age %></h4><br>
    <h4 id="weight">Current Weight: <%= @client.weight %></h4><br>
    <h4 id="goal">Goal: <%= @client.goal %></h4><br>
    <%= client_progress(@client) %>

    <br></br>
  </div>
  <div class="box">
    <h4>Notes:</h4>
    <ul class="notes-list">
      <% @notes.each do |note| %>
        <li><%= note.text %></li>
      <% end %>
    </ul>

    <br></br>
    
    <h4 class="note-header">Add a Note For <%= client_name(@client) %>:</h4>
    <%= form_for @note, :html=> {:id => 'note-form'} do |f| %>
      <%= f.hidden_field :client_id, value: @client.id %>
      <%= f.text_area :text %>
      <br></br>
      <%= f.submit "Add Note", :class => "btn btn-success btn-sm", :id => "ajax_submit" %>
    <% end %>
    <button id="clear-notes" data-id="<%= @client.id %>" class="btn btn-danger btn-sm">Clear Notes</button>
  </div>
</div>