config/routes.rb
Rails.application.routes.draw do

  root 'static#home'
  get '/dashboard', to: 'static#dashboard', as: 'dashboard'

  resources :users do
    # resources :appointments, only: [:index]
    resources :clients, only: [:new]
  end

  resources :clients, only: [:create, :edit, :update, :index, :show, :destroy] do
    resources :appointments, only: [:edit]
  end

  resources :notes, only: [:index, :create]

  delete '/notes', to: 'notes#destroy'

  resources :appointments, only: [:index, :update]
  resources :sessions, only: [:create]

  get 'clients/:id/appointment_complete', to: 'clients#appointment_complete', as: 'appointment_complete'
  patch 'clients/:id/update_progress', to: 'clients#update_progress', as: 'update_progress'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3><%= "Error(s):" %></h3>
  <ul>
  <% object.errors.full_messages.uniq.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    <% if !logged_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Log In", login_path, class: "navbutton" %></li>
        <li><%= link_to "Sign Up", signup_path, class: "navbutton" %></li>
        <li><%= link_to "Sign in with Facebook", "/auth/facebook", class: "navbutton", id: "sign_in" %></li>
      </ul>
    <% else %>
      <p class="navbar-brand">Signed in as: <%= current_user.name %></p>
      <ul class="nav navbar-nav">
        <% if current_page?(dashboard_path) %>
          <li><%= link_to "My Clients", clients_path, class: "navbutton load_clients" %></li>
          <li><%= link_to "My Appointments", appointments_path, class: "navbutton load_appointments" %></li>
        <% else %>
          <li><%= link_to "Dashboard", dashboard_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log Out", logout_path %></li>
      </ul>
    <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainerClientTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container">
      <%= content_tag(:div, flash[:alert], id: "flash_alert", class: "alert alert-danger") if flash[:alert] %>
      <br>
      <%= yield %>
    </div>
  </body>
</html>